# Generated by Django 3.2.9 on 2021-12-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imag',
            new_name='image',
        ),
    ]
