# Generated by Django 3.2.9 on 2021-12-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=500)),
                ('fb_link', models.URLField(max_length=400)),
                ('twitter_link', models.URLField(max_length=400)),
                ('instagram_link', models.URLField(max_length=400)),
            ],
        ),
    ]
