# Generated by Django 3.2.9 on 2021-12-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_name',
            field=models.CharField(max_length=220),
        ),
    ]
