# Generated by Django 3.2.9 on 2021-12-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyBook',
        ),
    ]
