# Generated by Django 3.2.9 on 2021-12-14 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='crated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
