# Generated by Django 3.2.9 on 2021-12-15 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_crated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='Property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='property.property'),
        ),
    ]
