# Generated by Django 3.2.9 on 2021-12-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertyimages_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimages',
            old_name='Property',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='propertyimages/'),
        ),
    ]
